# Atencao: Criar imagem usando como imagem base python:3.8-alpime
FROM python:

# Nao e' necessario atualizar nada aqui
WORKDIR /app
COPY source_code/ /app

# Atencao: Instalar dependencias definidas no arquivo requirements.txt
RUN

# Nao e' necessario atualizar nada aqui
ENTRYPOINT ["python", "server.py"]
